spring:
  application:
    name: eureka-service
server:
   port: 10111

eureka:
    instance:
      preferIpAddress: true
      ip-address: localhost
    client:
      registerWithEureka: false
      fetchRegistry: false
      serviceUrl:
        defaultZone: http://${eureka.instance.ip-address}:${server.port}/eureka/
    server:  #配置属性，但由于 Eureka 自我保护模式以及心跳周期长的原因，经常会遇到 Eureka Server 不剔除已关停的节点的问题
        #enable-self-preservation: false
      eviction-interval-timer-in-ms: 30000